name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Snyk version
        run: snyk -v

      - name: Snyk code scan
        run: snyk code test --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}

  scan-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Snyk dependency scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}
        with:
          args: --all-sub-projects --severity-threshold=high

  verify:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0 # disables husky hooks
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: lts/*

      - name: Verify
        run: make verify

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: 'coverage/clover.xml'
          threshold_alert: 80
          threshold_warning: 90
